# Generated by Django 2.2.4 on 2021-07-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suite_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='测试集合描述')),
                ('if_execute', models.IntegerField(default=0, verbose_name='是否执行')),
                ('test_case_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='测试执行模式')),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试集合',
                'verbose_name_plural': '测试集合',
            },
        ),
    ]
