# Generated by Django 2.2.4 on 2021-07-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_testcaseexecuterecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuitExecuteRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run_time_interval', models.IntegerField(default=0, null=True, verbose_name='延迟时间')),
                ('status', models.IntegerField(default=0, null=True, verbose_name='执行状态')),
                ('test_result', models.CharField(blank=True, max_length=50, null=True)),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('execute_start_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行开始时间')),
                ('test_suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.TestSuit', verbose_name='测试集合')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuitTestCaseExecuteRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0, null=True, verbose_name='执行状态')),
                ('exception_info', models.CharField(blank=True, max_length=500, null=True)),
                ('request_data', models.CharField(max_length=1024, null=True, verbose_name='请求体')),
                ('response_data', models.CharField(max_length=1024, null=True, verbose_name='响应字符串')),
                ('execute_result', models.CharField(max_length=1024, null=True, verbose_name='执行结果')),
                ('last_time_response_data', models.CharField(max_length=1024, null=True, verbose_name='上一次响应字符串')),
                ('execute_total_time', models.CharField(max_length=1024, null=True, verbose_name='执行耗时')),
                ('execute_start_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行开始时间')),
                ('execute_end_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='执行结束时间')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.TestCase', verbose_name='执行的测试用例')),
                ('test_suit_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.TestSuitExecuteRecord', verbose_name='执行的测试集合执行记录')),
            ],
        ),
    ]
